package pe

type Machine uint16

var (
	IMAGE_FILE_MACHINE_UNKNOWN   = Machine(0x0)
	IMAGE_FILE_MACHINE_AM33      = Machine(0x1d3)
	IMAGE_FILE_MACHINE_AMD64     = Machine(0x8664)
	IMAGE_FILE_MACHINE_ARM       = Machine(0x1c0)
	IMAGE_FILE_MACHINE_EBC       = Machine(0xebc)
	IMAGE_FILE_MACHINE_I386      = Machine(0x14c)
	IMAGE_FILE_MACHINE_IA64      = Machine(0x200)
	IMAGE_FILE_MACHINE_M32R      = Machine(0x9041)
	IMAGE_FILE_MACHINE_MIPS16    = Machine(0x266)
	IMAGE_FILE_MACHINE_MIPSFPU   = Machine(0x366)
	IMAGE_FILE_MACHINE_MIPSFPU16 = Machine(0x466)
	IMAGE_FILE_MACHINE_POWERPC   = Machine(0x1f0)
	IMAGE_FILE_MACHINE_POWERPCFP = Machine(0x1f1)
	IMAGE_FILE_MACHINE_R4000     = Machine(0x166)
	IMAGE_FILE_MACHINE_SH3       = Machine(0x1a2)
	IMAGE_FILE_MACHINE_SH3DSP    = Machine(0x1a3)
	IMAGE_FILE_MACHINE_SH4       = Machine(0x1a6)
	IMAGE_FILE_MACHINE_SH5       = Machine(0x1a8)
	IMAGE_FILE_MACHINE_THUMB     = Machine(0x1c2)
	IMAGE_FILE_MACHINE_WCEMIPSV2 = Machine(0x169)
)
